#!/usr/bin/env python3
"""Generate src/g29_descriptor.h - the report descriptor our fake wheel presents.

Layout taken from a GeForce NOW-accepted virtual G29 profile:
  hicwic/g25-w11-driver, virtual-g29/profiles/logitech-g29-usbip.json

That project reached the same conclusion we did about identity (GeForce NOW keys wheels on
VID:PID:bcdDevice), but on macOS their bcdDevice value 0x8900 makes the host refuse to
configure the interface at all - this board only attaches with 0x1350, which the macOS
client already accepted. So we keep our identity and borrow their *shape*, which is the
part of a wheel the game actually sees:

    bytes 0-3   hat (4 bits) + 25 buttons + 3 bits padding
    bytes 4-5   X, 16-bit, centre 32768
    bytes 6-8   Z (accelerator), Rz (brake), Y (clutch), 8-bit each, 255 = released
    bytes 9-11  vendor fields, the reference's inputDefaults values (0x81, 0x80, 0x9c)
    output      7-byte vendor report - the reference declares 16 (the lg4ff command plus
                padding), but our OUT endpoint and buffer are 7 wide and declaring more
                makes TinyUSB refuse the interface. The GeForce NOW client writes reports
                to match whatever the device declares, so 7 is what it already used.

Run:  ./tools/make_g29_descriptor.py
"""

import os
import sys

REFERENCE_HEX = (
    "05010904a1010939150025073500463b0165147504950181420509190129196500250145017501951981027501950381"
    "030501093027ffff000047ffff000075109501810209320935093126ff0046ff007508950381020600ff090195028102"
    "0600ff0901950181020600ff090226ff0046ff00951075089102c0"
)

# The one deviation from the reference: its 16-byte FFB output report is shrunk to the
# 7 bytes this board can actually serve. See the module docstring.
OUTPUT_ITEM_16 = bytes.fromhex("0600ff090226ff0046ff00951075089102")
OUTPUT_ITEM_7 = bytes.fromhex("0600ff090226ff0046ff00950775089102")

KINDS = {8: "input", 9: "output", 11: "feature"}
EXPECTED_BITS = {"input": 96, "output": 56}   # 12-byte input report, 7-byte FFB output report


def layout(descriptor: bytes) -> dict:
    """Walk the HID items and total up the bits per report kind, as a self-check."""
    i = 0
    size = 0
    count = 0
    totals: dict = {}
    while i < len(descriptor):
        prefix = descriptor[i]
        i += 1
        if prefix == 0xFE:                              # long item
            skip = descriptor[i]
            i += 2 + skip
            continue
        size_code = prefix & 0x03
        item_len = 4 if size_code == 3 else size_code
        item_type = (prefix >> 2) & 0x03
        tag = (prefix >> 4) & 0x0F
        value = int.from_bytes(descriptor[i:i + item_len], "little")
        i += item_len
        if item_type == 1 and tag == 7:                 # Report Size
            size = value
        elif item_type == 1 and tag == 9:               # Report Count
            count = value
        elif item_type == 0 and tag in KINDS:           # Input / Output / Feature
            kind = KINDS[tag]
            totals[kind] = totals.get(kind, 0) + size * count
    return totals


def main() -> int:
    descriptor = bytearray(bytes.fromhex(REFERENCE_HEX))
    at = descriptor.find(OUTPUT_ITEM_16)
    if at < 0:
        print("refusing to write: the vendor output report item was not found", file=sys.stderr)
        return 1
    descriptor[at:at + len(OUTPUT_ITEM_16)] = OUTPUT_ITEM_7
    descriptor = bytes(descriptor)

    totals = layout(descriptor)
    for kind, bits in EXPECTED_BITS.items():
        if totals.get(kind) != bits:
            print(f"refusing to write: {kind} is {totals.get(kind)} bits, expected {bits}",
                  file=sys.stderr)
            return 1

    here = os.path.dirname(os.path.abspath(__file__))
    header = os.path.join(here, "..", "src", "g29_descriptor.h")
    body = "\n".join("    " + " ".join(f"0x{b:02x}," for b in descriptor[j:j + 10])
                     for j in range(0, len(descriptor), 10))
    try:
        with open(header, "w", encoding="utf-8") as handle:
            handle.write("/* Generated by tools/make_g29_descriptor.py - do not hand-edit.\n"
                         " * GeForce NOW-accepted G29 field layout (hicwic/g25-w11-driver\n"
                         " * virtual-g29/profiles/logitech-g29-usbip.json), with the FFB output\n"
                         " * report shrunk from 16 to 7 bytes to match this board's endpoint:\n"
                         f" * {totals['input']}-bit input report ({-(-totals['input'] // 8)} bytes), "
                         f"{totals['output']}-bit vendor FFB output report ({totals['output'] // 8} bytes).\n"
                         " * Hat+25 buttons in bytes 0-3, steering 16-bit at 4-5, accelerator/brake/\n"
                         " * clutch (Z/Rz/Y) at 6-8, vendor bytes 9-11. */\n")
            handle.write("static const uint8_t g29_report_descriptor[] = {\n")
            handle.write(body + "\n};\n")
    except OSError as err:
        print(f"cannot write {header}: {err}", file=sys.stderr)
        return 1

    print(f"wrote {header} ({len(descriptor)} bytes), layout {totals}, "
          f"input {-(-totals['input'] // 8)} bytes, output {totals['output'] // 8} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
