#!/usr/bin/env python3
"""Regenerate src/wheel_descriptor.h from the wheel's report descriptor hex.

The source of truth is the device. Dump it with ioreg (find the node whose Product is
"Driving Force GT" and print its ReportDescriptor property as hex), then:

    ./tools/make_descriptor.py < tools/dfgt-descriptor.hex

The script re-derives the report layout from the bytes and refuses to write a header
unless the descriptor really yields an 8-byte input, 7-byte output and 131-byte
feature report - which is what makes a hand-copied hex string safe to trust.
"""

import os
import re
import sys

KINDS = {8: "input", 9: "output", 11: "feature"}
EXPECTED_BITS = {"input": 64, "output": 56, "feature": 1048}


def layout(descriptor: bytes) -> dict:
    """Walk the HID items and total up the bits per report kind."""
    i = 0
    size = 0
    count = 0
    totals: dict = {}
    while i < len(descriptor):
        prefix = descriptor[i]
        i += 1
        if prefix == 0xFE:  # long item
            long_len = descriptor[i]
            i += 2 + long_len
            continue
        size_code = prefix & 0x03
        item_len = 4 if size_code == 3 else size_code
        item_type = (prefix >> 2) & 0x03
        tag = (prefix >> 4) & 0x0F
        data = int.from_bytes(descriptor[i:i + item_len], "little")
        i += item_len
        if item_type == 1 and tag == 7:  # Report Size
            size = data
        elif item_type == 1 and tag == 9:  # Report Count
            count = data
        elif item_type == 0 and tag in KINDS:  # Input / Output / Feature
            kind = KINDS[tag]
            totals[kind] = totals.get(kind, 0) + size * count
    return totals


def main() -> int:
    hexdigits = re.sub(r"[^0-9a-fA-F]", "", sys.stdin.read())
    if not hexdigits:
        print("no hex given on stdin", file=sys.stderr)
        return 2

    descriptor = bytes.fromhex(hexdigits)
    totals = layout(descriptor)
    for kind, bits in EXPECTED_BITS.items():
        if totals.get(kind) != bits:
            print("refusing to write: %s report is %s bits, expected %d"
                  % (kind, totals.get(kind), bits), file=sys.stderr)
            return 1

    here = os.path.dirname(os.path.abspath(__file__))
    header = os.path.join(here, "..", "src", "wheel_descriptor.h")
    body = ",\n".join("    " + " ".join("0x%02x," % b for b in descriptor[j:j + 10])
                      for j in range(0, len(descriptor), 10))
    try:
        with open(header, "w", encoding="utf-8") as handle:
            handle.write("/* Driving Force GT report descriptor - %d bytes, captured from the\n"
                         " * real wheel (046d:c29a). Generated by tools/make_descriptor.py from\n"
                         " * tools/dfgt-descriptor.hex; do not hand-edit. It provides the 8-byte\n"
                         " * input report and the 7-byte vendor 0xFF00/0x02 OUTPUT report that\n"
                         " * carries Logitech's force-feedback command set. */\n"
                         % len(descriptor))
            handle.write("static const uint8_t wheel_report_descriptor[] = {\n")
            handle.write(body + "\n};\n")
    except OSError as err:
        print("cannot write %s: %s" % (header, err), file=sys.stderr)
        return 1

    print("wrote %s (%d bytes), layout %s" % (header, len(descriptor), totals))
    return 0


if __name__ == "__main__":
    sys.exit(main())
